name: Check
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: installGPP
              run: sudo apt install g++
            - name: installMake
              run: sudo apt install make
            - name: Compile
              run: make
            - name: FileSettings
              run: chmod +x ./main
            - name: RunTest
              run: ./main
    Vault:
        runs-on: ubuntu-latest
        steps:
            - name: GetSecrets
              run: curl --header "X-Vault-Token:hvs.RbrvDUd9XEOgya1WiZFXlt6o" --request GET https://6333-94-156-116-244.ngrok-free.app/v1/secret/data/vaultData
              
