name: Check
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: installGPP
              run: sudo apt install g++
            - name: installMake
              run: sudo apt install make
            - name: CleanObj
              run: make clean
            - name: Compile
              run: make all
            - name: FileSettings
              run: chmod +x ./main
            - name: RunTest
              run: ./main
    Vault:
        runs-on: ubuntu-latest
        steps:
            - name: installingJq
              run: sudo apt install jq
            - name: GetSecrets
              env:
                  VAULT_ADDRESS: ${{ secrets.VAULT_ADDRESS }} 
                  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }} 
              run: curl --header "X-Vault-Token:$VAULT_TOKEN" --request GET $VAULT_ADDRESS/v1/secret/data/vaultData | jq -r ".data.data"
              
